default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost


development:
  <<: *default
  database: kamilmazitovdb
  username: mazitov479admin
  password: <%= ENV['KAMILMAZITOVDB_PASSWORD'] %>


test:
  <<: *default
  database: kamilmazitovdb
  username: mazitov479admin
  password: <%= ENV['KAMILMAZITOVDB_PASSWORD'] %>

production:
  <<: *default
  database: kamilmazitovdb
  username: mazitov479admin
  password: <%= ENV['KAMILMAZITOVDB_PASSWORD'] %>